/**
 * CORTEX DECISION INTELLIGENCE — DASHBOARD TYPES (team control room)
 *
 * Domain: leads, diagnostics, recommendations, proposals, CRM, ROI tracking.
 * Import dashboard/UI types from THIS file — not from `cortex-data-schema.ts`.
 *
 * Pipeline-stage equivalents live in `cortex-data-schema.ts` with `Schema*` names
 * (e.g. `SchemaCoreProblem`, `SchemaPillarScore`). Client-facing report data uses
 * `ClientReportData` from `@/app/utils/clientReportGenerator`.
 *
 * BACKEND IMPLEMENTATION:
 * When implementing real backend, each interface represents data that needs to be:
 * 1. Generated by AI analysis of diagnostic responses
 * 2. Stored in database
 * 3. Returned via API endpoints
 * 4. Updated based on team actions and learning loop
 */

// ============================================================================
// LEAD & DIAGNOSTIC DATA
// ============================================================================

export type LeadStatus =
  | 'new'
  | 'needs-review'
  | 'ready-for-call'
  | 'proposal-sent'
  | 'converted'
  | 'disqualified';

export type ReadinessLevel = 'Low' | 'Medium' | 'High';

export type ConfidenceScore = 'Low' | 'Medium' | 'High' | 'Very High';

export interface Lead {
  id: string;
  companyName: string;
  contactEmail: string;
  industry: string;
  companySize: string;
  submittedAt: string;

  // AI-Generated Scores
  readinessScore: ReadinessLevel;
  confidenceScore: ConfidenceScore;
  primaryPainSignal: string;  // Auto-detected main problem

  // Status & Pipeline
  status: LeadStatus;
  assignedTo?: string;
  lastActivityAt: string;

  // Quick metrics
  urgencyLevel: number;  // 0-10
  impactPotential: number;  // 0-10
}

// ============================================================================
// DIAGNOSTIC SUMMARY
// ============================================================================

export interface CoreProblem {
  title: string;
  whatsbroken: string;
  whyBreaking: string;
  whatBreaksNext: string;
  urgencyScore: number;  // 0-10
  editable: boolean;
  /** Which question IDs informed this problem (answer-to-bottleneck tracing) */
  sourceAnswers?: number[];
  /** Bottleneck category ID (maps to questionRegistry BOTTLENECK_CATEGORIES) */
  bottleneckId?: string;
}

export type PillarScore = 0 | 1 | 2 | 3 | 4 | 5;

export interface PillarHeatmap {
  operationsExecution: PillarScore;
  revenueGrowth: PillarScore;
  systemsAutomation: PillarScore;
  aiReadinessGovernance: PillarScore;
}

export interface RiskFlag {
  type: string;
  label: string;
  description: string;
  severity: 'critical' | 'high' | 'medium';
}

// ── NEW: Bottleneck Deep Dive structures (Section B) ─────────────────────────

export type BottleneckSeverity = 'Moderate' | 'High' | 'Critical';
export type BottleneckCategory = 'Revenue' | 'Operations' | 'Governance' | 'Compliance';

export interface EvidenceItem {
  questionRef: string;       // e.g. "Q3"
  questionId: number;
  clientExcerpt: string;     // short excerpt from the answer
  aiInterpretation: string;  // AI analysis of what this means
  structuralImplication: string; // what this means at the system level
}

export interface BottleneckDeepDive {
  id: string;                                     // "B1", "B2", etc.
  title: string;
  severity: BottleneckSeverity;
  category: BottleneckCategory;
  patternStrength: number;                         // numeric, higher = stronger

  causalChain: [string, string, string, string, string]; // Trigger → Immediate → Secondary → Compounding → Failure

  stressSimulation: {
    growth_20_percent: string;
    growth_30_percent: string;
    founder_absence: string;
    system_failure: string;
  };

  rootCauseHierarchy: {
    level_1_symptom: string;
    level_2_process_failure: string;
    level_3_architecture_failure: string;
    level_4_governance_failure: string;
  };

  quantifiedImpact: {
    revenue_leakage_estimate: number;              // annual $
    payroll_inflation_risk: number;                // annual $
    time_waste_hours_per_week: number;
    growth_ceiling_percent: number;                // %
  };

  intervention: {
    short_term: string;
    mid_term: string;
    structural_redesign: string;
  };

  evidence: EvidenceItem[];

  /** Link back to bottleneck ID */
  bottleneckId?: string;
}

// ── NEW: Cross-System Pattern (Section C) ────────────────────────────────────

export interface SystemicPattern {
  patternName: string;
  severity: 'Low' | 'Moderate' | 'High';
  signalCount: number;
  crossDepartmentalPresence: boolean;
  failureCascadePotential: string;
  recurrenceProbability: number;                    // 0-1 float
}

// ── NEW: Pillar Interpretation (Section D) ───────────────────────────────────

export interface PillarInterpretation {
  interpretation: string;
  dominantWeakness: string;
  automationLeveragePotential: string;
}

export type PillarInterpretations = Record<keyof PillarHeatmap, PillarInterpretation>;

// ── NEW: Financial & Efficiency Model (Section E) ────────────────────────────

export interface FinancialEfficiencyModel {
  directRevenuLeakage: number;
  hiddenOperationalDrag: number;
  payrollMisallocation: number;
  opportunityCost: number;
  compoundingGrowthTax: number;
  totalEstimatedAnnualImpact: number;
  // Pre-formatted strings for UI
  directRevenuLeakageFormatted: string;
  hiddenOperationalDragFormatted: string;
  payrollMisallocationFormatted: string;
  opportunityCostFormatted: string;
  compoundingGrowthTaxFormatted: string;
  totalEstimatedAnnualImpactFormatted: string;
}

// ── NEW: Enhanced Risk Assessment (Section F) ────────────────────────────────

export type RiskCategory = 'Scalability' | 'Data Integrity' | 'Dependency' | 'Compliance';
export type RiskType = 'Scalability' | 'Data' | 'Dependency' | 'Compliance';

export interface EnhancedRiskFlag {
  riskType: RiskType;
  severity: 'Low' | 'Moderate' | 'High' | 'Critical';
  triggerThreshold: string;
  probabilityPercent: number;
  timeToFailureEstimate: string;
  cascadePath: string;
}

// ── NEW: Confidence & Integrity Layer ─────────────────────────────────────────

export interface ConfidenceLayer {
  totalSignalsDetected: number;
  corroboratedPatterns: number;
  contradictionFlags: number;
  weakSignalFlags: number;
  aiConfidenceScore: number;            // 0-1 float
}

// ── NEW: Executive Diagnostic Overview (Section A) ───────────────────────────

export type ReadinessCategory = 'Manual' | 'Fragmented' | 'Transitional' | 'Structured';

export interface ExecutiveOverview {
  readinessScore: number;          // 0-100
  readinessCategory: ReadinessCategory;
  confidenceLevel: string;         // e.g. "High (87%)"
  growthRiskIndicator: 'Critical' | 'Elevated' | 'Moderate' | 'Low';
  primaryBottleneckTheme: string;
  primaryBottleneckId: string;     // e.g. "B1"
  secondaryBottleneck: string;
  secondaryBottleneckId: string;   // e.g. "B2"
  estimatedAnnualImpactRange: string; // e.g. "$180K–$320K"
  summaryNarrative: string;           // 3-5 lines max
  confidenceScore: number;            // 0-100
}

// ── Updated Diagnostic Summary ───────────────────────────────────────────────

export interface DiagnosticSummary {
  leadId: string;

  // Top 3 core problems (legacy)
  coreProblems: CoreProblem[];

  // Pillar scores
  pillarHeatmap: PillarHeatmap;

  // Risk flags (legacy)
  riskFlags: RiskFlag[];

  // Raw responses (for reference — legacy format)
  allResponses: {
    question: string;
    answer: string;
    category: string;
  }[];

  /** Fully annotated Q&A with signal detection and bottleneck linking */
  annotatedResponses?: import('@/app/utils/questionRegistry').AnnotatedResponse[];
  /** Reverse map: bottleneckId → questionIds that informed it */
  bottleneckSourceMap?: Record<string, number[]>;

  // ── NEW structured sections ──
  /** Section A — Executive Diagnostic Overview */
  executiveOverview?: ExecutiveOverview;
  /** Section B — Primary Bottleneck Deep Dive */
  bottleneckDeepDives?: BottleneckDeepDive[];
  /** Section C — Cross-System Patterns */
  systemicPatterns?: SystemicPattern[];
  /** Section D — Pillar Interpretations */
  pillarInterpretations?: PillarInterpretations;
  /** Section E — Financial & Efficiency Model */
  financialModel?: FinancialEfficiencyModel;
  /** Section F — Enhanced Risk Assessment */
  enhancedRisks?: EnhancedRiskFlag[];
  /** Section G — Confidence & Integrity Layer */
  confidenceLayer?: ConfidenceLayer;
}

// ============================================================================
// AI RECOMMENDATION ENGINE
// ============================================================================

export type ServiceType =
  | 'operations-audit'
  | 'ai-implementation'
  | 'automation-sprint'
  | 'systems-integration'
  | 'strategic-roadmap'
  | 'founder-leverage';

export type RecommendationStatus = 'pending' | 'accepted' | 'modified' | 'overridden';

export interface ServiceRecommendation {
  primaryService: ServiceType;
  primaryServiceLabel: string;

  // Why this service first
  reasoning: string;

  // What NOT to do yet
  notRecommended: {
    service: string;
    reason: string;
  }[];

  // 90-day focus
  focusAreas: string[];

  // Timeline
  suggestedTimeline: string;

  // Team actions
  recommendationStatus: RecommendationStatus;
  overrideReason?: string;
  modifiedBy?: string;
  modifiedAt?: string;

  /** Detailed implementation blueprint (Phase 2 enhancement) */
  solutionBlueprint?: SolutionBlueprint;

  // ── v1 schema extensions ──────────────────────────────────────────────────

  /** Confidence in the recommendation (0-1 float) */
  confidenceScore?: number;

  /** Quantified expected impact */
  expectedImpact?: RecommendationExpectedImpact;

  /** Implementation window in days */
  implementationWindowDays?: number;

  /** Financial investment summary */
  investmentSummary?: RecommendationInvestmentSummary;

  /** v2 schema — full structured recommendation payload */
  recommendationV2?: import('@/app/core/types').RecommendationV2;

  /** Business Transformation Portfolio — multi-department recommendations */
  portfolio?: import('@/app/core/types').BusinessTransformationPortfolio;

  /** Decision Transparency — why math chose this recommendation */
  decisionTransparency?: import('@/app/core/types').DecisionTransparency;
}

// ── v1 Recommendation sub-types ──────────────────────────────────────────────

export interface RecommendationExpectedImpact {
  revenueLiftPercent: number;
  costReductionPercent: number;
  timeSavedHoursMonth: number;
}

export interface RecommendationInvestmentSummary {
  estimatedCostRange: string;         // e.g. "$15K–$30K"
  paybackPeriodWeeks: string;         // e.g. "6–10 weeks"
  roiPercent12Month: string;          // e.g. "320%"
}

// ============================================================================
// SOLUTION BLUEPRINT (DETAILED OPERATIONAL PLAN)
// ============================================================================

/** Blueprint implementation phase — used inside SolutionBlueprint (legacy recommendation engine) */
export interface BlueprintPhase {
  name: string;
  duration: string;          // e.g. "Days 1-10"
  objectives: string[];
  deliverables: {
    item: string;
    description: string;
  }[];
  teamRequired: string[];
  milestones: {
    day: string;
    milestone: string;
  }[];
  linkedBottleneck?: string; // Which core problem this phase addresses
  risksMitigated: string[];
}

export interface BlueprintKPI {
  metric: string;
  baseline: string;
  target30: string;
  target60: string;
  target90: string;
  measurementMethod: string;
}

export interface BlueprintRisk {
  risk: string;
  probability: 'low' | 'medium' | 'high';
  impact: 'low' | 'medium' | 'high';
  mitigation: string;
  owner: string;
}

export interface SolutionBlueprint {
  executiveSummary: string;
  phases: BlueprintPhase[];
  kpis: BlueprintKPI[];
  riskRegister: BlueprintRisk[];
  investmentSummary: {
    totalRange: string;
    breakdownByPhase: { phase: string; range: string }[];
    paybackPeriod: string;
    roiTimeline: string;
  };
  resourcePlan: {
    role: string;
    allocation: string;
    phase: string;
  }[];
}

// ============================================================================
// ROI & IMPACT ESTIMATES
// ============================================================================

export interface ROIEstimate {
  hoursSavedPerMonth: {
    conservative: number;
    aggressive: number;
  };
  costAvoidedPerMonth: {
    conservative: number;
    aggressive: number;
  };
  revenueLeakageReduced: {
    conservative: number;
    aggressive: number;
  };
  operationalRiskReduction: 'low' | 'medium' | 'high' | 'very-high';

  // Editable team notes
  notes: string;
  confidenceLevel: 'needs-validation' | 'conservative' | 'aggressive';

  /** Phase 3: Enhanced financial modeling */
  monthlyProjections?: MonthlyProjection[];
  scenarioComparison?: ScenarioComparison;
  breakEvenAnalysis?: BreakEvenAnalysis;
  editableAssumptions?: ROIAssumption[];
}

export interface MonthlyProjection {
  month: number;          // 1-12
  label: string;          // "Month 1", "Month 2", etc.
  hoursSaved: number;
  costAvoided: number;
  revenueRecovered: number;
  cumulativeROI: number;  // Running total savings
  investmentToDate: number;
  netValue: number;       // cumulativeROI - investmentToDate
}

export interface ScenarioComparison {
  scenarios: {
    name: string;         // "Conservative", "Expected", "Aggressive"
    color: string;
    totalInvestment: number;
    year1Return: number;
    roi: number;          // percentage
    paybackMonths: number;
    netPresentValue: number;
  }[];
}

export interface BreakEvenAnalysis {
  breakEvenMonth: number;
  totalInvestment: number;
  monthlyBenefit: number;
  confidenceRange: { low: number; high: number }; // month range
}

export interface ROIAssumption {
  id: string;
  label: string;
  value: number;
  unit: string;         // "$", "hours", "%", etc.
  min: number;
  max: number;
  category: 'cost' | 'savings' | 'revenue';
  description: string;
}

// ============================================================================
// PROPOSAL CONTROL & EXPORT — Phase 5
// ============================================================================

export interface ProposalState {
  status:      ProposalStatus;
  locked:      boolean;
  sent_at:     string | null;
  viewed_at:   string | null;
  approved_at: string | null;
  expires_at:  string | null;
  approved_by: string | null;
}

export interface ClientView {
  roi_scenario:                'expected_only';
  hide_internal_metrics:       boolean;
  hide_confidence_scores:      boolean;
  simplify_financial_language: boolean;
}

export type ExportType = 'executive_pdf' | 'detailed_pdf' | 'internal_review_pdf';

export interface ApprovalBlock {
  signature_required:        boolean;
  payment_terms:             string;
  contract_reference_required: boolean;
}

export interface SignatureBlock {
  client_representative_name: string;
  title:                      string;
  date:                       string | null;
  authorized:                 boolean;
}

// ============================================================================
// PROPOSAL DRAFT — proposal-data-model.json Phase 1
// ============================================================================

export type ProposalStatus =
  | 'draft'
  | 'review'
  | 'internal_review'
  | 'financial_binding'
  | 'approved'
  | 'ready_to_send'
  | 'sent'
  | 'viewed'
  | 'rejected'
  | 'expired';

export type DiagnosisSeverity = 'critical' | 'high' | 'medium' | 'low';
export type EvidenceSource = 'questionnaire' | 'ops_pattern' | 'team_assessment' | 'financial_data';

export interface DiagnosisEvidence {
  source: EvidenceSource;
  ref: string;
  note: string;
}

export interface DiagnosisBlock {
  diagnosis_id: string;
  title: string;
  description: string;
  operational_impact: string[];
  financial_impact: string[];
  evidence: DiagnosisEvidence[];
  severity: DiagnosisSeverity;
  confidence: number;   // 0–100
}

export interface ProposalDraft {
  proposal_id: string;
  status: ProposalStatus;
  client: {
    client_id: string;
    company_name: string;
    industry: string;
    region: string;
    primary_contact: {
      name: string;
      title: string;
      email: string;
    };
  };
  linkage: {
    diagnostic_id: string;
    portfolio_version_id: string;
    generated_from: ('diagnostic' | 'recommendations' | 'roi')[];
  };
  /** Editable by team */
  executive_brief: {
    title: string;
    strategic_context: string;
    why_now: string;
    what_success_looks_like: string;
    positioning_statement: string;
  };
  /** Editable by team */
  diagnosis_blocks: DiagnosisBlock[];
  /** Editable by team */
  scope_boundaries: {
    included: string[];
    excluded: string[];
    assumptions: string[];
  };
  /** next_step_offer.price editable; rest read-only */
  next_step_offer: {
    offer_name: string;
    price: number;
    currency: string;
    duration: string;
    primary_cta: string;
    secondary_cta: string;
  };
  /** Solution Architecture — diagnosis → solution binding (Phase 2) */
  solutions?: Solution[];
  /** Implementation Phase Timeline — solution → phase assignment (Phase 2) */
  implementation_phases?: ImplementationPhase[];
  /** Financial Summary — auto-populated from ROI engine (Phase 3). Manual edits blocked. */
  financial_summary?: FinancialSummary;
  /** Implementation Architecture — who, when, how, what systems (Phase 4). Editable by team. */
  implementation_plan?: ImplementationPlan;
  /** Proposal State Machine — lifecycle control (Phase 5). */
  proposal_state?: ProposalState;
  /** Client-Facing Simplification Layer — controls what client sees (Phase 5). */
  client_view?: ClientView;
  /** Approval & Signature Block — export contract precursor (Phase 5). */
  approval_block?: ApprovalBlock;
  /** Signature capture — client representative (Phase 5). */
  signature_block?: SignatureBlock;
  /** System-managed; increments on every edit */
  metadata: {
    created_at: string;
    last_updated_at: string;
    created_by: string;
    version: number;
  };
}

// ============================================================================
// PROPOSAL BUILDER (legacy)
// ============================================================================

export type PricingBand = '$5K-$10K' | '$10K-$20K' | '$20K-$50K' | '$50K-$100K' | '$100K+';

export interface ProposalData {
  leadId: string;

  // Auto-populated from diagnostic
  clientContext: string;
  diagnosedProblems: string[];
  recommendedServicePath: string;

  // Timeline
  timeline: '30-days' | '60-days' | '90-days' | 'custom';

  // Pricing
  pricingBand: PricingBand;
  pricingLocked: boolean;

  // Scope
  scopeItems: string[];
  exclusions: string[];

  // Notes
  upsellNotes: string;

  // Status
  generatedAt?: string;
  sentAt?: string;
  lastModifiedBy?: string;
}

// ============================================================================
// CALL PREP PANEL
// ============================================================================

export interface CallPrep {
  leadId: string;

  // Auto-generated agenda
  suggestedAgenda: string[];

  // Validation questions
  keyQuestionsToValidate: string[];

  // Expected objections
  expectedObjections: {
    objection: string;
    response: string;
  }[];

  // Warnings
  doNotPitchYetWarnings: string[];

  // Expansion signals
  expansionSignalsToListenFor: string[];

  // Call scheduled?
  scheduledFor?: string;
  callNotes?: string;
}

// ============================================================================
// DECISION & STATUS FLOW
// ============================================================================

export interface DecisionLog {
  leadId: string;
  timestamp: string;
  fromStatus: LeadStatus;
  toStatus: LeadStatus;
  reason: string;
  actionTakenBy: string;
  notes?: string;
}

export interface NextAction {
  leadId: string;
  action: string;
  priority: 'urgent' | 'high' | 'medium' | 'low';
  dueDate?: string;
  assignedTo?: string;
}

// ============================================================================
// LEARNING LOOP (THE MOAT)
// ============================================================================

export interface OutcomeFeedback {
  leadId: string;

  // Conversion
  didConvert: boolean;
  conversionValue?: number;

  // Recommendation accuracy
  recommendationWorked: boolean;
  whichRecommendationWorked?: string;
  whichDidntWork?: string;
  whyDidntWork?: string;

  // Insights
  whatWeLearned: string;

  // System improvements
  suggestedImprovements: {
    area: 'scoring' | 'recommendation' | 'risk-detection' | 'timeline' | 'pricing';
    improvement: string;
  }[];

  // Logged
  loggedAt: string;
  loggedBy: string;
}

export interface LearningInsights {
  // Overall stats
  totalLeadsAnalyzed: number;
  conversionRate: number;

  // Accuracy metrics
  recommendationAccuracy: number;
  scoringAccuracy: number;

  // By industry
  industryPerformance: {
    industry: string;
    conversionRate: number;
    avgDealSize: number;
    bestRecommendation: string;
  }[];

  // Recent improvements
  recentImprovements: {
    date: string;
    improvement: string;
    impact: string;
  }[];
}

// ============================================================================
// COMPLETE CORTEX DATA
// ============================================================================

export interface CortexLeadData {
  lead: Lead;
  diagnostic: DiagnosticSummary;
  recommendation: ServiceRecommendation;
  roiEstimate: ROIEstimate;
  /** ROI Modeling Layer — deterministic, formula-driven */
  roiModel?: import('@/app/core/types').PortfolioROIModel;
  /** Portfolio State — version control + assumptions */
  portfolioState?: import('@/app/core/types').PortfolioState;
  /** Proposal Draft v1 — proposal-data-model.json first-class artifact */
  proposal_draft?: ProposalDraft;
  proposal?: ProposalData;
  callPrep?: CallPrep;
  decisionLog: DecisionLog[];
  nextActions: NextAction[];
  outcomeFeedback?: OutcomeFeedback;
}

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

export const getReadinessColor = (level: ReadinessLevel): string => {
  switch (level) {
    case 'High': return '#10B981';
    case 'Medium': return '#FB923C';
    case 'Low': return '#FD4438';
  }
};

export const getPillarColor = (score: PillarScore): string => {
  if (score >= 4) return '#10B981';  // Green - stable
  if (score >= 2) return '#FB923C';  // Yellow - fix soon
  return '#FD4438';  // Red - urgent
};

export const getStatusColor = (status: LeadStatus): { bg: string; text: string; border: string } => {
  switch (status) {
    case 'new':
      return { bg: '#8B5CF6', text: '#F5F5FF', border: '#8B5CF6' };
    case 'needs-review':
      return { bg: '#FB923C', text: '#FFF', border: '#FB923C' };
    case 'ready-for-call':
      return { bg: '#3B82F6', text: '#FFF', border: '#3B82F6' };
    case 'proposal-sent':
      return { bg: '#06D7F6', text: '#0A0A0F', border: '#06D7F6' };
    case 'converted':
      return { bg: '#10B981', text: '#FFF', border: '#10B981' };
    case 'disqualified':
      return { bg: '#70707C', text: '#FFF', border: '#70707C' };
    default:
      // Fallback for any unexpected status values
      return { bg: '#8B5CF6', text: '#F5F5FF', border: '#8B5CF6' };
  }
};

export const getServiceLabel = (service: ServiceType): string => {
  switch (service) {
    case 'operations-audit': return 'Operations Audit';
    case 'ai-implementation': return 'AI Implementation';
    case 'automation-sprint': return 'Automation Sprint';
    case 'systems-integration': return 'Systems Integration';
    case 'strategic-roadmap': return 'Strategic Roadmap';
    case 'founder-leverage': return 'Founder Leverage Package';
  }
};

/**
 * API INTEGRATION POINTS
 *
 * Backend endpoints needed:
 *
 * GET /api/cortex/leads
 * - Returns: Lead[]
 * - Purpose: Get all leads with basic info
 *
 * GET /api/cortex/lead/:id
 * - Returns: CortexLeadData
 * - Purpose: Get complete data for one lead
 *
 * POST /api/cortex/analyze/:submissionId
 * - Body: { submissionId: string }
 * - Returns: CortexLeadData
 * - Purpose: Trigger AI analysis of a new submission
 *
 * PUT /api/cortex/lead/:id/status
 * - Body: { status: LeadStatus, reason: string }
 * - Returns: { success: boolean }
 * - Purpose: Update lead status
 *
 * PUT /api/cortex/lead/:id/recommendation
 * - Body: { status: RecommendationStatus, overrideReason?: string }
 * - Returns: { success: boolean }
 * - Purpose: Accept/modify/override AI recommendation
 *
 * POST /api/cortex/lead/:id/proposal
 * - Body: ProposalData
 * - Returns: { success: boolean, proposalUrl: string }
 * - Purpose: Generate and save proposal
 *
 * POST /api/cortex/lead/:id/feedback
 * - Body: OutcomeFeedback
 * - Returns: { success: boolean }
 * - Purpose: Log outcome for learning loop
 *
 * GET /api/cortex/insights
 * - Returns: LearningInsights
 * - Purpose: Get system-wide learning insights
 */

// ============================================================================
// SOLUTION ARCHITECTURE — solution-architecture-binding.md
// ============================================================================

export type SolutionPillar = 'workflow' | 'agents' | 'revenue' | 'monitoring';

export interface SolutionFinancialLevers {
  efficiency_gain: number;   // % 0–100
  revenue_uplift:  number;   // % 0–100
  cost_reduction:  number;   // % 0–100
  risk_mitigation: number;   // % 0–100
}

export interface SolutionImplementationScope {
  systems_affected:   string[];
  automation_layers:  string[];
  ai_components:      string[];
  integration_points: string[];
}

export interface Solution {
  solution_id:                   string;
  title:                         string;
  pillar:                        SolutionPillar;
  linked_diagnosis_ids:          string[];
  root_problem_addressed:        string;
  system_description:            string;
  implementation_scope:          SolutionImplementationScope;
  expected_operational_outcomes: string[];
  financial_levers:              SolutionFinancialLevers;
  dependencies:                  string[];
  risk_flags:                    string[];
  complexity_score:              number;  // 1–5
  confidence_score:              number;  // 0–100
  /** Financial Binding — auto-populated from ROI engine (Phase 3). Manual edits blocked. */
  financial_binding?:            SolutionFinancialBinding;
}

export interface ImplementationPhase {
  phase_number:   number;
  title:          string;
  duration_weeks: number;
  solution_ids:   string[];
  deliverables:   string[];
}

// ============================================================================
// FINANCIAL SUMMARY BINDING — financial-summary-binding-1.md
// ============================================================================

export interface MonteCarloStats {
  mean_roi:                 number;  // %
  median_roi:               number;  // %
  p10_roi:                  number;  // % — pessimistic 10th percentile
  p90_roi:                  number;  // % — optimistic 90th percentile
  probability_positive_roi: number;  // % 0–100
}

export interface FinancialSummary {
  /** Must match ProposalDraft.linkage.portfolio_version_id — mismatch → Phase 3 gate fails */
  portfolio_version_id:      string;
  scenario:                  'conservative' | 'expected' | 'optimistic';
  currency:                  string;
  investment_total:          number;
  annual_gain_conf_weighted: number;
  roi_percentage:            number;
  payback_month:             number;
  npv:                       number;
  irr_annual:                number;   // %
  irr_monthly:               number;   // %
  monte_carlo:               MonteCarloStats;
  confidence_score:          number;   // 0–100; gate requires ≥ 70
  realization_factor_applied: boolean;
  dependency_validated:      boolean;
  roi_cap_applied:           boolean;
}

export interface SolutionFinancialBinding {
  investment_allocated:        number;
  annual_gain:                 number;
  roi_contribution_percentage: number;  // % of total portfolio ROI
  payback_month:               number;
}

// ============================================================================
// IMPLEMENTATION ARCHITECTURE LAYER — implementation-architecture.md
// ============================================================================

export type GovernanceCheckpointType =
  | 'internal_validation'
  | 'client_review'
  | 'sign_off'
  | 'roi_recheck';

export interface ImplementationMilestone {
  week:         number;
  title:        string;
  owner:        string;
  deliverables: string[];
}

export interface GovernanceCheckpoint {
  type:         GovernanceCheckpointType;
  required:     boolean;
  description?: string;
}

export interface ImplementationPlanPhase {
  phase_number:           number;
  title:                  string;
  duration_weeks:         number;
  solution_ids:           string[];
  milestones:             ImplementationMilestone[];
  governance_checkpoints: GovernanceCheckpoint[];
}

export interface TeamMember {
  role:               string;
  responsibility:     string;
  involvement_phase:  number[];
}

export interface TeamStructure {
  cortex_team:          TeamMember[];
  client_team_required: TeamMember[];
}

export interface IntegrationArchitecture {
  systems_affected:        string[];
  data_sources:            string[];
  automation_tools:        string[];
  ai_models_used:          string[];
  security_considerations: string[];
}

export interface GovernanceControls {
  human_in_loop:                    boolean;
  approval_required_for_automation: boolean;
  quarterly_review:                 boolean;
  roi_revalidation_required:        boolean;
}

export interface ImplementationPlan {
  phases:                   ImplementationPlanPhase[];
  team_structure:           TeamStructure;
  integration_architecture: IntegrationArchitecture;
  governance_controls:      GovernanceControls;
}

// ============================================================================
// CONTRACT AUTO-GENERATION — Phase 6
// ============================================================================

export type ContractStatus = 'draft' | 'sent' | 'signed';
export type PaymentStructure = 'upfront_milestone' | 'fixed_fee' | 'retainer';

export interface ContractDeliverable {
  deliverable_id: string;
  solution_id:    string;
  title:          string;
  description:    string;
  acceptance_criteria: string[];
}

export interface ContractMilestone {
  milestone_id:       string;
  phase_number:       number;
  title:              string;
  duration_weeks:     number;
  payment_percentage: number;   // % of total due at this milestone
  deliverable_ids:    string[];
}

export interface PaymentScheduleItem {
  label:       string;
  amount:      number;
  due_trigger: string;
  percentage:  number;
}

export interface LegalBlock {
  id:      string;
  title:   string;
  text:    string;
  editable: false;
}

export interface ContractPayload {
  contract_id:              string;
  proposal_id:              string;
  generated_at:             string;
  client_legal_name:        string;
  engagement_scope:         ContractDeliverable[];
  exclusions:               string[];
  milestones:               ContractMilestone[];
  investment:               number;
  currency:                 string;
  payment_structure:        PaymentStructure;
  payment_terms:            string;
  payment_schedule:         PaymentScheduleItem[];
  liability_limits:         string;
  confidentiality_clause:   true;
  data_protection_clause:   true;
  termination_clause:       string;
  signature_required:       true;
  legal_blocks:             LegalBlock[];
  status:                   ContractStatus;
  sent_at:                  string | null;
  signed_at:                string | null;
  kickoff_triggered:        boolean;
  /** Snapshot of portfolio_version_id at generation time — used to detect ROI drift */
  roi_version_snapshot?:    string;
}

// ============================================================================
// OBJECTION HANDLING INTELLIGENCE — Phase 6
// ============================================================================

export type ObjectionType = 'price' | 'risk' | 'timing' | 'trust' | 'internal_alignment';

export interface ObjectionDetected {
  type:       ObjectionType;
  confidence: number;   // 0.0–1.0
  at_risk:    boolean;  // confidence > 0.7
}

export interface ObjectionPlaybook {
  type:            ObjectionType;
  label:           string;
  response_points: string[];
  email_subject:   string;
  email_body:      string;
}

// ============================================================================
// CRM SYNCHRONIZATION LAYER — Phase 7
// Spec: crm-sync-spec.md
// ============================================================================

/** 14 locked canonical pipeline stages */
export type CRMStage =
  | 'lead_captured'
  | 'diagnostic_started'
  | 'diagnostic_completed'
  | 'proposal_draft'
  | 'proposal_sent'
  | 'proposal_viewed'
  | 'negotiation_objection'
  | 'approved_pending_contract'
  | 'contract_sent'
  | 'contract_signed'
  | 'onboarding_started'
  | 'implementation_active'
  | 'closed_won'
  | 'closed_lost';

/** All event types that can trigger a CRM sync */
export type CRMActivityType =
  | 'deal_created'
  | 'diagnostic_started'
  | 'diagnostic_completed'
  | 'proposal_created'
  | 'proposal_ready_to_send'
  | 'proposal_sent'
  | 'proposal_viewed'
  | 'objection_detected'
  | 'proposal_approved'
  | 'proposal_rejected'
  | 'contract_generated'
  | 'contract_sent'
  | 'contract_signed'
  | 'onboarding_started'
  | 'implementation_started'
  | 'project_completed';

export interface CRMActivityLog {
  activity_id: string;
  deal_id:     string;
  type:        CRMActivityType;
  /** Arbitrary JSON payload — proposal_id, timestamps, confidence, etc. */
  payload:     Record<string, unknown>;
  created_at:  string;
}

export type CRMTaskStatus = 'open' | 'done';

export interface CRMTask {
  task_id:     string;
  deal_id:     string;
  assigned_to: string;
  task_type:   string;
  due_at:      string;   // ISO date
  status:      CRMTaskStatus;
  notes:       string;
  /** Derived at render time — not stored */
  overdue?:    boolean;
}

export interface CRMDeal {
  deal_id:           string;
  client_id:         string;
  proposal_id:       string | null;
  contract_id:       string | null;
  owner_user_id:     string;
  stage:             CRMStage;
  value_estimate:    number;
  close_probability: number;   // 0–1
  created_at:        string;
  updated_at:        string;
  activity:          CRMActivityLog[];
  tasks:             CRMTask[];
}

// ============================================================================
// POST-IMPLEMENTATION ROI TRACKING ENGINE — Phase 8
// Spec: roi-tracking-spec.md
// ============================================================================

export type BaselineQuality = 'low' | 'medium' | 'high';

/** 9 locked variance reason tags from spec §5 */
export type VarianceReasonTag =
  | 'adoption_delay'
  | 'data_quality_issue'
  | 'scope_change'
  | 'integration_blocker'
  | 'stakeholder_bottleneck'
  | 'tool_limitations'
  | 'model_performance'
  | 'underestimated_change_mgmt'
  | 'positive_outlier';

/** Baseline metrics snapshot — captured at contract_signed / onboarding_started */
export interface BaselineMetrics {
  ticket_volume_per_week:        number;
  response_time_hours:           number;   // avg ticket / query response
  admin_hours_per_week:          number;
  lead_response_time_hours:      number;
  conversion_rate_pct:           number;   // 0–100
  proposal_cycle_days:           number;
  tool_costs_monthly:            number;   // $
  headcount_involved:            number;
}

/** roi_baselines record — Spec §1 */
export interface ROIBaseline {
  baseline_id:          string;
  deal_id:              string;
  proposal_id:          string;
  portfolio_version_id: string;
  captured_at:          string;
  metrics_snapshot:     BaselineMetrics;
  baseline_quality:     BaselineQuality;
  notes:                string;
}

/** roi_actuals record — one row per month — Spec §1 + §3 */
export interface ROIActualsEntry {
  actual_id:               string;
  deal_id:                 string;
  period_start:            string;   // YYYY-MM-01
  period_end:              string;   // YYYY-MM-last
  period_label:            string;   // "Month 1", "Month 2"
  metrics: {
    actual_monthly_gain:       number;
    actual_monthly_investment: number;
    net_actual:                number;
    cumulative_actual:         number;
  };
  notes:                   string;
  captured_by:             string;
  created_at:              string;
}

/** roi_variance record — one row per period — Spec §4 */
export interface ROIVariance {
  variance_id:            string;
  deal_id:                string;
  period:                 string;
  period_label:           string;
  projected: {
    monthly_gain:         number;
    monthly_investment:   number;
    cumulative:           number;
  };
  actual: {
    monthly_gain:         number;
    monthly_investment:   number;
    cumulative:           number;
  };
  delta: {
    variance_gain:              number;   // actual - projected
    variance_pct:               number;   // %
    variance_payback_shift:     number;   // months shifted (+ = delay, - = accelerated)
  };
  variance_reason_tags:   VarianceReasonTag[];
}

/** roi_solution_attribution record — Spec §1 */
export interface ROISolutionAttribution {
  deal_id:                    string;
  solution_id:                string;
  solution_title:             string;
  period:                     string;
  projected_gain:             number;
  actual_gain:                number;
  confidence_adjusted_actual: number;
  realization_factor:         number;   // actual / projected; < 1 = under, > 1 = over
  notes:                      string;
}

/** Rolled-up realization factors per industry — Spec §6 */
export interface RealizationFactorRecord {
  industry:                   string;
  efficiency_realization_actual: number;
  revenue_realization_actual:    number;
  sample_count:               number;
  last_updated_at:            string;
}