// MANUFACTURING / SUPPLY CHAIN / INDUSTRIAL QUESTIONS
export const industrialQuestions = [
  // 1️⃣ BUSINESS & PRODUCTION REALITY (3)
  {
    id: 1,
    category: 'Business & Production Reality',
    question: 'Describe what you manufacture or distribute, how production flows today, and where value is actually created.',
    type: 'textarea' as const,
    placeholder: 'Describe your core operations and production flow...',
    motivationalQuote: "Understanding your value creation process is the first step to optimizing it.",
    exampleAnswers: [
      "Contract manufacturer - precision metal parts for automotive industry. Value in tight tolerances and JIT delivery. Raw material → CNC machining → QC → finishing → packaging → ship.",
      "Food/beverage co-packer: Receive bulk ingredients → mixing/blending → bottling → labeling → palletizing → warehouse → distribute. Value is in quality control and compliance.",
      "Industrial distributor: Don't manufacture, but warehouse and distribute HVAC components. Value in inventory availability and fast fulfillment.",
      "Custom fabrication shop: Engineer-to-order approach. Quote → design → material procurement → fabrication → assembly → install. Value is customization and problem-solving.",
    ],
    backgroundTheme: 'industry',
  },
  {
    id: 2,
    category: 'Business & Production Reality',
    question: 'What happens when orders increase by 20–30%? What part of production, fulfillment, or coordination breaks first?',
    type: 'textarea' as const,
    placeholder: 'Identify your scale constraints...',
    motivationalQuote: "Growth constraints reveal your next operational priority.",
    exampleAnswers: [
      "Production scheduling collapses - manually managed, can't juggle priorities, missed deadlines, customer complaints",
      "Material shortages - purchasing can't keep up, run out of critical components, production sits idle",
      "Quality suffers - rushing to meet demand leads to errors, rework, scrap, customer returns",
      "Warehouse chaos - can't find inventory, shipping errors increase, receiving backs up",
      "Me - I become the bottleneck approving everything, making all coordination calls, working 80-hour weeks",
      "Labor shortage - can't hire/train fast enough, existing team burns out from overtime",
    ],
    backgroundTheme: 'challenge',
  },
  {
    id: 3,
    category: 'Business & Production Reality',
    question: 'Which production, purchasing, or operational decisions still depend on you or senior managers?',
    type: 'textarea' as const,
    placeholder: 'List your leadership dependencies...',
    motivationalQuote: "Delegation and systems free leaders to focus on strategy, not firefighting.",
    exampleAnswers: [
      "Production priorities and schedule changes - only I know customer relationships and strategic importance",
      "Purchasing decisions for all non-standard items - team doesn't have supplier knowledge or authority",
      "Quality decisions - accepting or rejecting marginal parts, determining rework vs scrap",
      "Customer negotiations on pricing, delivery changes, custom requests",
      "Hiring, firing, overtime approval, capital equipment purchases",
      "Problem-solving production issues - team escalates everything instead of being empowered",
    ],
    backgroundTheme: 'team',
  },

  // 2️⃣ OPERATIONS, PROCESSES & BOTTLENECKS (4)
  {
    id: 4,
    category: 'Operations, Processes & Bottlenecks',
    question: 'Where do delays, idle time, rework, or handoff issues occur most often?',
    type: 'textarea' as const,
    placeholder: 'Map your production bottlenecks...',
    motivationalQuote: "Eliminating bottlenecks unlocks capacity without capital investment.",
    exampleAnswers: [
      "Between departments - work sits waiting for next process because no visibility or coordination",
      "Material delays - waiting for components, purchasing doesn't know what production needs when",
      "Rework loops - quality issues discovered late, batch already moved downstream, costly to fix",
      "Machine setup time excessive - lack of standardization, each operator does it differently",
      "Handoff between shifts - incomplete communication, work repeated or mistakes made",
      "Engineering changes - updates don't cascade properly, old specs used, scrap results",
    ],
    backgroundTheme: 'efficiency',
  },
  {
    id: 5,
    category: 'Operations, Processes & Bottlenecks',
    question: 'Which tasks still rely on phone calls, WhatsApp, emails, or spreadsheets to "keep things moving"?',
    type: 'textarea' as const,
    placeholder: 'Identify manual coordination pain points...',
    motivationalQuote: "Manual coordination doesn't scale. Systems do.",
    exampleAnswers: [
      "Production scheduling is a daily morning phone call and whiteboard session - chaos when people are absent",
      "Inventory tracking via spreadsheet - constantly out of sync with reality, physical counts to reconcile",
      "Purchase orders and vendor communication all via email - things get lost, no tracking or audit trail",
      "Shop floor updates via WhatsApp group chat - critical information buried in message history",
      "Shipping/receiving uses paper logs - manually entered into computer later, errors and delays",
      "Customer order status requires manually checking multiple systems and calling around to update",
    ],
    backgroundTheme: 'challenge',
  },
  {
    id: 6,
    category: 'Operations, Processes & Bottlenecks',
    question: 'Where do errors happen — and how late are they usually discovered?',
    type: 'textarea' as const,
    placeholder: 'Describe quality and error leakage...',
    motivationalQuote: "Early error detection saves exponentially more than late discovery.",
    exampleAnswers: [
      "Wrong materials used - discovered at final QC or worse, at customer site. Extremely costly.",
      "Specification errors - work order has wrong dimensions, full batch produced incorrectly",
      "Shipping errors - wrong items/quantities sent to customers, expensive expedited corrections required",
      "Inventory inaccuracies - think we have stock but don't, production halted unexpectedly",
      "Quality issues caught at final inspection - entire batch needs rework, delays and cost overruns",
      "Documentation errors - compliance/traceability issues discovered during audits",
    ],
    backgroundTheme: 'tools',
  },
  {
    id: 7,
    category: 'Operations, Processes & Bottlenecks',
    question: 'If these inefficiencies continue for 12 months, what is the real cost? (Waste, overtime, missed orders, staff burnout, lost clients.)',
    type: 'textarea' as const,
    placeholder: 'Quantify the cost of operational dysfunction...',
    motivationalQuote: "Inefficiency tax compounds daily. Calculate it honestly.",
    exampleAnswers: [
      "Overtime and firefighting mode is costing $150K+ annually just in labor premium, plus burnout and turnover",
      "Scrap and rework eating 8-12% of material cost - that's $300K walking into the dumpster",
      "Lost orders - can't meet delivery promises, customers going to competitors, revenue impact $500K+",
      "Inventory carrying costs and obsolescence from poor planning - $200K tied up unnecessarily",
      "Quality claims and customer returns - reputation damage plus direct cost $100K annually",
      "Can't take on larger contracts or new customers - growth ceiling hit, opportunity cost massive",
    ],
    backgroundTheme: 'revenue',
  },

  // 3️⃣ SYSTEMS, DATA & VISIBILITY (4)
  {
    id: 8,
    category: 'Systems, Data & Visibility',
    question: 'List the systems used for: Production planning, Inventory, Purchasing, Logistics, Reporting.',
    type: 'textarea' as const,
    placeholder: 'Document your complete system landscape...',
    motivationalQuote: "System fragmentation creates blind spots and inefficiency.",
    exampleAnswers: [
      "Production: Excel and whiteboard | Inventory: Partial in QuickBooks, rest in spreadsheet | Purchasing: Email + Excel | Logistics: Third-party but we don't see into it | Reporting: Manual assembly from all of the above",
      "Old ERP system from 2005 - barely use it, most features broken or ignored, supplemented with 20+ spreadsheets",
      "Production: Paper work orders | Inventory: Periodic physical counts, no real-time | Purchasing: Informal/tribal knowledge | Reporting: Don't have reliable data",
      "Mix of systems: QuickBooks for accounting, custom Access database (someone built years ago), Excel trackers, paper shop floor",
      "Trying to implement new MRP system but stalled halfway - running parallel with old methods, double work, teams frustrated",
    ],
    backgroundTheme: 'tools',
  },
  {
    id: 9,
    category: 'Systems, Data & Visibility',
    question: 'Which systems don\'t talk to each other and force double entry or manual reconciliation?',
    type: 'textarea' as const,
    placeholder: 'Identify system integration failures...',
    motivationalQuote: "Every manual data transfer is an error waiting to happen.",
    exampleAnswers: [
      "Accounting system and production system completely separate - manually reconciling inventory values monthly",
      "Customer orders entered into CRM, then manually re-entered into production system, then into shipping system",
      "Purchasing and inventory don't sync - constantly updating both systems, discrepancies everywhere",
      "Quality data collected on paper, then manually typed into database for analysis",
      "Time tracking separate from production tracking - can't tie labor costs to specific jobs automatically",
      "Each department has their own spreadsheets - end of month is a nightmare reconciling everything",
    ],
    backgroundTheme: 'challenge',
  },
  {
    id: 10,
    category: 'Systems, Data & Visibility',
    question: 'What do you not have real-time visibility into today? (Inventory, production status, delays, costs, demand.)',
    type: 'textarea' as const,
    placeholder: 'Describe your operational blind spots...',
    motivationalQuote: "Real-time visibility transforms reactive management into proactive leadership.",
    exampleAnswers: [
      "Actual inventory levels - only know via physical counts, surprised by stockouts regularly",
      "Production status - can't tell customers where their order is without walking the floor and asking around",
      "True job costing - don't know if we made or lost money on a job until weeks after completion",
      "Equipment utilization and downtime - no data on what's actually constraining throughput",
      "Supplier delivery performance - constantly surprised by late deliveries disrupting production",
      "Quality trends - identify problems only when they become crises, no early warning signals",
    ],
    backgroundTheme: 'efficiency',
  },
  {
    id: 11,
    category: 'Systems, Data & Visibility',
    question: 'How long does it take to get a clear operational or financial picture?',
    type: 'textarea' as const,
    placeholder: 'Describe your reporting reality...',
    motivationalQuote: "Delayed insights lead to delayed decisions and missed opportunities.",
    exampleAnswers: [
      "Monthly financials take 2-3 weeks to close - operating on seriously outdated information",
      "Operational reporting assembled manually, takes days of work, often contains errors",
      "Can't answer 'how are we doing this month' without spending hours gathering data",
      "Don't have KPI dashboards - rely on gut feel and anecdotal information",
      "Board/investor reporting is a quarterly nightmare - all-hands-on-deck data scramble",
      "Customer profitability analysis? Would take weeks to compile, so we just guess",
    ],
    backgroundTheme: 'tools',
  },

  // 4️⃣ AI READINESS & FUTURE STATE (3)
  {
    id: 12,
    category: 'AI Readiness & Future State',
    question: 'Have you attempted automation or digital transformation before? What failed or stalled?',
    type: 'textarea' as const,
    placeholder: 'Share your transformation history...',
    motivationalQuote: "Past failures contain the lessons for future success.",
    exampleAnswers: [
      "Bought expensive ERP system 5 years ago - implementation was a disaster, never fully deployed, expensive shelf-ware",
      "Tried barcode scanning for inventory - worked for a month then people reverted to old habits, no enforcement",
      "Automation project on production line - equipment unreliable, maintenance couldn't support it, scrapped it",
      "Digital work orders - shop floor hated tablets, went back to paper because 'easier'",
      "Data analytics initiative - hired consultants, got fancy reports nobody understood or used",
      "Never tried - overwhelmed by options, afraid of disruption, don't know where to start",
    ],
    backgroundTheme: 'challenge',
  },
  {
    id: 13,
    category: 'AI Readiness & Future State',
    question: 'What must never be automated without strict control? (Compliance, safety, audits, customer commitments.)',
    type: 'textarea' as const,
    placeholder: 'Define your automation constraints...',
    motivationalQuote: "Smart automation respects critical constraints while eliminating waste.",
    exampleAnswers: [
      "Safety and compliance protocols - regulatory requirements, certifications, audit trails must be maintained",
      "Final quality inspection - human judgment still required for complex acceptance criteria",
      "Customer-facing communication - relationships matter, can't fully automate",
      "Critical purchasing decisions - vendor relationships and risk management require human oversight",
      "Production schedule overrides - need human judgment for strategic prioritization",
      "Custom engineering work - automation can assist but can't replace expertise",
      "Financial approvals over certain thresholds - fiduciary responsibility requires human accountability",
    ],
    backgroundTheme: 'team',
  },
  {
    id: 14,
    category: 'AI Readiness & Future State',
    question: 'If this worked perfectly, what would run smoother, faster, or cheaper without more headcount?',
    type: 'textarea' as const,
    placeholder: 'Paint your operational transformation vision...',
    motivationalQuote: "Clear vision of the future state guides every transformation decision.",
    exampleAnswers: [
      "Real-time visibility - know inventory, production status, costs instantly. Make better decisions faster.",
      "Automated scheduling - system optimizes production flow, reduces lead times 30-40%, eliminates daily chaos",
      "Inventory optimization - right materials at right time, reduce carrying costs, eliminate stockouts and emergency orders",
      "Quality tracking - catch errors early in process, not at final inspection. Reduce scrap and rework by half.",
      "Labor efficiency - eliminate double data entry and searching for information, focus on value-adding work",
      "Customer self-service - order status, quotes, documentation available 24/7 without staff intervention",
      "Predictive maintenance - equipment issues flagged before failure, reduce downtime and emergency repairs",
    ],
    backgroundTheme: 'revenue',
  },
];
