// UNIVERSAL CORTEX DIAGNOSTIC - OTHER / ANY BUSINESS
export const universalQuestions = [
  // 1️⃣ BUSINESS REALITY & MODEL (3)
  {
    id: 1,
    category: 'Business Reality & Model',
    question: 'Describe what your business does, who you serve, and how money comes in today.',
    type: 'textarea' as const,
    placeholder: 'Tell us about your business in your own words...',
    motivationalQuote: "Clarity about your business model is the foundation of optimization.",
    exampleAnswers: [
      "We're a boutique consulting firm serving mid-sized manufacturers. Revenue comes from retainer contracts and project-based engagements. Currently 15 active clients.",
      "Online marketplace connecting freelance designers with small businesses. Revenue from transaction fees (15%) and premium seller subscriptions ($50/mo).",
      "B2B wholesale distributor of industrial supplies. Revenue from product markup, primarily serving construction companies in the Southeast.",
      "Professional services firm - mix of training workshops, one-on-one coaching, and digital course sales. 60% workshops, 30% coaching, 10% courses.",
      "Family-owned retail chain with 8 locations. Revenue from product sales with 35% gross margins. Mix of walk-in and growing online sales.",
    ],
    backgroundTheme: 'industry',
  },
  {
    id: 2,
    category: 'Business Reality & Model',
    question: 'How do you deliver value to customers (service, product, digital, physical, hybrid)?',
    type: 'textarea' as const,
    placeholder: 'Describe your delivery model...',
    motivationalQuote: "Understanding your delivery model reveals optimization opportunities.",
    exampleAnswers: [
      "Fully digital: SaaS platform delivered via web app and mobile, customers self-serve, support via chat and email",
      "Hybrid: Physical products shipped, plus digital content and community access via membership portal",
      "Service-based: In-person consulting and training at client sites, some follow-up via Zoom and Slack",
      "Product + service: Sell equipment, then ongoing maintenance contracts and consumables",
      "Pure service: Done-for-you work, deliverables sent digitally, all communication virtual",
      "Marketplace model: Connect buyers and sellers, facilitate transactions, take commission",
    ],
    backgroundTheme: 'efficiency',
  },
  {
    id: 3,
    category: 'Business Reality & Model',
    question: 'If demand increased by 30% tomorrow, what part of the business would break first?',
    type: 'textarea' as const,
    placeholder: 'Identify your breaking point...',
    motivationalQuote: "Your current constraints reveal your next growth opportunity.",
    exampleAnswers: [
      "Customer support would collapse - already stretched thin, can't handle more volume without major delays",
      "Fulfillment/delivery - production capacity maxed out, or logistics can't scale fast enough",
      "Me personally - I'm the bottleneck for approvals, decisions, customer relationships",
      "Sales pipeline - could handle more customers but struggle to close and onboard them",
      "Quality control - rushing to meet demand would lead to errors and customer dissatisfaction",
      "Cash flow - don't have capital to purchase inventory or hire ahead of revenue",
    ],
    backgroundTheme: 'challenge',
  },

  // 2️⃣ OPERATIONS & EXECUTION PAIN (4)
  {
    id: 4,
    category: 'Operations & Execution Pain',
    question: 'What tasks or processes slow your team down every day?',
    type: 'textarea' as const,
    placeholder: 'List your daily bottlenecks...',
    motivationalQuote: "Daily friction compounds into massive lost opportunity over time.",
    exampleAnswers: [
      "Hunting for information - emails, messages, files scattered everywhere. Takes 20-30 min to find context.",
      "Status updates and meetings - spending hours in meetings just to share information that could be automated",
      "Manual data entry - same information entered into multiple systems, prone to errors",
      "Waiting for approvals - work sits in queues waiting for sign-off from busy managers",
      "Customer inquiries - answering the same questions repeatedly, could be self-service",
      "Coordinating schedules - back-and-forth to book meetings and allocate resources",
    ],
    backgroundTheme: 'efficiency',
  },
  {
    id: 5,
    category: 'Operations & Execution Pain',
    question: 'Which decisions or approvals still require you personally?',
    type: 'textarea' as const,
    placeholder: 'List your personal bottlenecks...',
    motivationalQuote: "Distributing decision-making authority multiplies organizational capacity.",
    exampleAnswers: [
      "All customer-facing communication - team doesn't have confidence or authority to respond independently",
      "Pricing, proposals, contracts - only I understand margins and strategic considerations",
      "Hiring decisions, vendor selection, any purchase over $1000",
      "Quality approval - I review every deliverable before it goes to customers",
      "Problem-solving - team escalates every non-standard situation to me for resolution",
      "Strategic priorities and resource allocation - only I see the full picture",
    ],
    backgroundTheme: 'team',
  },
  {
    id: 6,
    category: 'Operations & Execution Pain',
    question: 'List the most repetitive tasks your team does weekly.',
    type: 'textarea' as const,
    placeholder: 'Identify repetitive work patterns...',
    motivationalQuote: "Every repetitive task is an automation opportunity waiting to be seized.",
    exampleAnswers: [
      "Creating reports by manually copying data from 5 different systems into spreadsheets",
      "Sending follow-up emails and reminders to customers, vendors, team members",
      "Data entry - customer info, orders, transactions entered manually",
      "Scheduling and calendar management - coordinating availability across people and resources",
      "Invoice generation and payment follow-ups - repetitive, time-consuming, error-prone",
      "Onboarding new customers - same steps every time but done manually each time",
      "Social media posting and content distribution - manual process across platforms",
    ],
    backgroundTheme: 'tools',
  },
  {
    id: 7,
    category: 'Operations & Execution Pain',
    question: 'What do these inefficiencies cost you in time, money, or missed opportunities?',
    type: 'textarea' as const,
    placeholder: 'Quantify the cost of inefficiency...',
    motivationalQuote: "The cost of inefficiency is often invisible until you calculate it.",
    exampleAnswers: [
      "Lost revenue: Turning away business because we can't handle more volume - easily $200-300K annually",
      "Wasted labor: Team spending 30-40% of time on administrative overhead instead of value creation",
      "Margin erosion: Inefficiency eating 10-15% of gross margin - that's real profit disappearing",
      "Opportunity cost: Can't pursue growth initiatives because stuck in operational quicksand",
      "Team burnout: High turnover, recruiting and training costs, loss of institutional knowledge",
      "Personal toll: Working 60-70 hour weeks unsustainably, health and relationships suffering",
      "Customer churn: Slow responses and inconsistent quality driving customers to competitors",
    ],
    backgroundTheme: 'revenue',
  },

  // 3️⃣ SYSTEMS, DATA & VISIBILITY (4)
  {
    id: 8,
    category: 'Systems, Data & Visibility',
    question: 'What tools do you currently use across sales, operations, finance, and support?',
    type: 'textarea' as const,
    placeholder: 'List your complete tool stack...',
    motivationalQuote: "Your tool ecosystem should enable work, not create it.",
    exampleAnswers: [
      "Sales: HubSpot CRM | Operations: Asana + Google Sheets | Finance: QuickBooks | Support: Email + Zendesk",
      "Mostly Google Workspace (Gmail, Sheets, Docs), QuickBooks, Trello, Slack, and lots of spreadsheets",
      "Salesforce (barely use it), Excel for everything, email for customer support, manual accounting",
      "Minimal tech stack - email, spreadsheets, basic accounting software, paper processes",
      "Too many tools: Bought various SaaS solutions but poor adoption, teams still use old methods",
      "Custom-built system from years ago (painful to maintain) plus random point solutions",
    ],
    backgroundTheme: 'tools',
  },
  {
    id: 9,
    category: 'Systems, Data & Visibility',
    question: 'Where do tools fail to connect, causing double work or confusion?',
    type: 'textarea' as const,
    placeholder: 'Identify integration gaps and friction...',
    motivationalQuote: "Integrated systems create single sources of truth, not chaos.",
    exampleAnswers: [
      "CRM and accounting don't sync - manually entering customers and transactions in both places",
      "Email is our integration layer - everything flows through email because systems don't talk",
      "Project management disconnected from time tracking - can't see true project profitability",
      "Customer data scattered across 4 systems - no single source of truth, constant discrepancies",
      "Reporting requires manual data gathering from multiple sources - takes days to compile",
      "Team uses different tools for similar tasks - can't get unified visibility across organization",
    ],
    backgroundTheme: 'challenge',
  },
  {
    id: 10,
    category: 'Systems, Data & Visibility',
    question: 'What information do you wish you could see in real time but can\'t?',
    type: 'textarea' as const,
    placeholder: 'Describe your visibility gaps...',
    motivationalQuote: "Data visibility transforms reactive management into proactive leadership.",
    exampleAnswers: [
      "Real-time P&L and cash position - currently only know financial reality weeks after month-end",
      "Sales pipeline health and forecast accuracy - what's actually going to close vs wishful thinking",
      "Team capacity and workload - who's overloaded, who has bandwidth, where to allocate work",
      "Customer health and churn risk - which customers are happy, which are at risk, why",
      "Operational metrics - efficiency, quality, throughput, bottlenecks in real-time",
      "True profitability by customer, product, or service line - are we actually making money?",
    ],
    backgroundTheme: 'efficiency',
  },
  {
    id: 11,
    category: 'Systems, Data & Visibility',
    question: 'How long does it take to understand business performance today?',
    type: 'textarea' as const,
    placeholder: 'Describe your reporting reality...',
    motivationalQuote: "Delayed insights lead to delayed decisions and missed opportunities.",
    exampleAnswers: [
      "Monthly financials close 2-3 weeks after month-end - making decisions on stale data",
      "No real-time dashboards - have to manually compile reports, takes 2-3 days of work",
      "Can answer 'how are we doing?' only with gut feel and anecdotal evidence",
      "Quarterly board reporting is a nightmare - weeks of data gathering and reconciliation",
      "Basic metrics available but deeper analysis requires significant manual work",
      "Some automated reporting but missing key operational metrics, tells incomplete story",
    ],
    backgroundTheme: 'tools',
  },

  // 4️⃣ AI READINESS & FUTURE STATE (3)
  {
    id: 12,
    category: 'AI Readiness & Future State',
    question: 'Have you tried automation, AI, or digital systems before? What didn\'t work?',
    type: 'textarea' as const,
    placeholder: 'Share your transformation history...',
    motivationalQuote: "Past attempts teach you what to avoid and what to prioritize.",
    exampleAnswers: [
      "Bought expensive software that never got properly implemented - now it's shelf-ware",
      "Tried Zapier automations but they kept breaking - didn't have expertise to maintain them",
      "Chatbot for customer service was terrible - customers hated it, we turned it off",
      "Email marketing automation works well - one of few successes, ready to expand automation",
      "Started CRM implementation but stalled halfway - team resistance, poor training, competing priorities",
      "Never tried - intimidated by complexity, concerned about cost and disruption",
      "Multiple attempts failed due to lack of clear process documentation and change management",
    ],
    backgroundTheme: 'challenge',
  },
  {
    id: 13,
    category: 'AI Readiness & Future State',
    question: 'What parts of the business must stay tightly controlled or human-approved?',
    type: 'textarea' as const,
    placeholder: 'Define your control boundaries...',
    motivationalQuote: "Constraints focus innovation on solutions that actually fit your reality.",
    exampleAnswers: [
      "Brand voice and customer-facing communication - can't compromise on personal touch and quality",
      "Financial approvals over certain thresholds - fiduciary responsibility requires human oversight",
      "Strategic decisions and partnerships - need human judgment and relationship considerations",
      "Quality control for deliverables - can automate parts but final approval stays human",
      "Data security and privacy - especially sensitive customer/patient information",
      "Hiring and personnel decisions - too important and nuanced to automate",
      "Legal and compliance matters - require expert human review and sign-off",
    ],
    backgroundTheme: 'team',
  },
  {
    id: 14,
    category: 'AI Readiness & Future State',
    question: 'If AI worked perfectly, what would improve without hiring more people?',
    type: 'textarea' as const,
    placeholder: 'Paint your transformation vision...',
    motivationalQuote: "A clear vision of success guides every decision along the way.",
    exampleAnswers: [
      "Time liberation: I work 40 hours instead of 70, team focused on creative work instead of admin",
      "Revenue growth: 30-50% increase without adding headcount - better systems, higher efficiency",
      "Customer experience: Faster responses, more consistent quality, proactive rather than reactive",
      "Real-time intelligence: Make data-driven decisions instantly instead of flying blind",
      "Profit expansion: Same revenue but 15-20% better margins from operational efficiency",
      "Team satisfaction: Less frustration with broken processes, more time for meaningful work",
      "Scalability: Business runs smoothly when I'm away, not dependent on any single person",
    ],
    backgroundTheme: 'revenue',
  },
];
