/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Current Supabase project (cortex): https://oqybniefkbppptfatoae.supabase.co
export const projectId = "oqybniefkbppptfatoae"
// The anon/publishable key is NOT baked into source. Provide it at build/deploy
// time via VITE_SUPABASE_ANON_KEY (or VITE_SUPABASE_PUBLISHABLE_KEY), which
// src/config/supabase.config.ts reads before falling back to this value.
export const publicAnonKey = ""